logging:
  level:
    web: DEBUG
    org.springframework.amqp: DEBUG
    org.springframework.security: DEBUG
    org.springframework.integration: DEBUG
    org.springframework.data.mongodb: DEBUG
    com.hookiesolutions.webhookie: TRACE
