spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://webhookie.au.auth0.com/
          jwk-set-uri: https://webhookie.au.auth0.com/.well-known/jwks.json
          jws-algorithm: RS256
webhookie:
  security:
    audience: ${WH_SECURITY_AUD:account}
    login-url: http://localhost:8080
    roles:
      jwk-json-path: $['https://webhookie.com/roles'] # if autoAssign is false and cannot find WH_CONSUMER then respond with 403
      auto-assign-consumer: true
      role-mapping:
        USER: WH_USER
        ADMIN: WH_ADMIN
        PROVIDER: WH_PROVIDER
        CONSUMER: WH_CONSUMER