spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8000/auth/realms/webhookie
          jwk-set-uri: http://127.0.0.1:8000/auth/realms/webhookie/protocol/openid-connect/certs
          jws-algorithm: RS256
webhookie:
  security:
    iam-aud:
      json-path: $.aud[0]
      value: account
    login-url: http://localhost:8080
    roles:
      jwk-json-path: $.realm_access.roles # if autoAssign is false and cannot find WH_CONSUMER then respond with 403
      auto-assign-consumer: true
      role-mapping:
        USER: WH_CONSUMER
        ADMIN: WH_ADMIN
        PROVIDER: WH_PROVIDER
        ROLE1: WH_CONSUMER
