webhookie:
  consumer:
    queue: ${WH_CONSUMER_QUEUE:wh-customer.event}
    missing-header:
      exchange: ${WH_CONSUMER_MISSING_HEADER_EXCHANGE:wh-customer}
      routing-key: ${WH_CONSUMER_MISSING_HEADER_ROUTING_KEY:wh-missing-header}
spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USERNAME}:${DB_PASSWORD}@${DB_URI}/${DB_NAME}?retryWrites=true&w=majority
  rabbitmq:
    host: ${WH_AMQP_HOST}
    virtual-host: ${WH_AMQP_V_HOST}
    username: ${WH_AMQP_USERNAME}
    password: ${WH_AMQP_PASSWORD}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  info:
    git:
      mode: full
logging:
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} - %X{dd.trace_id:-0} %X{dd.span_id:-0} - %m%n%wEx"
