webhookie:
  consumer:
    queue: ${WH_CONSUMER_QUEUE:wh-customer.event}
    missing-header:
      exchange: ${WH_CONSUMER_MISSING_HEADER_EXCHANGE:wh-customer}
      routing-key: ${WH_CONSUMER_MISSING_HEADER_ROUTING_KEY:wh-missing-header}
  subscription:
    retry:
      max-retry: 3
      initial-interval: 10
      multiplier: 2
  security:
    audience: ${WH_SECURITY_AUD:account}
    client-id: ${WH_SECURITY_CLIENT_ID:webhookie-client}
    groups:
      jwk-json-path: ${WH_SECURITY_GROUPS_JSON_PATH:$.groups}
    oauth2:
      authorization-uri: ${WH_SECURITY_OAUTH2_AUTHORIZATION_URI:/protocol/openid-connect/auth}
      token-uri: ${WH_SECURITY_OAUTH2_TOKEN_URI:/protocol/openid-connect/token}
      token-name: ${WH_SECURITY_OAUTH2_TOKEN_NAME:access_token}
    entity:
      jwk-json-path: ${WH_SECURITY_ENTITY_JSON_PATH:$.entity}
    roles:
      jwk-json-path: ${WH_SECURITY_ROLES_JSON_PATH:$.realm_access.roles}
      auto-assign-consumer: ${WH_SECURITY_AUTO_ASSIGN_CONSUMER_ROLE:true}
    no-auth:
      pathMatchers:
        OPTIONS: /**
        GET: /actuator/**, /swagger-ui.html**, /v3/**, /webjars/swagger-ui/**, /public/**
mongodb:
  encrypt:
    keys:
      - version: 1
        key: hqHKBLV83LpCqzKpf8OvutbCs+O5wX5BPu3btWpEvXA=
spring:
  config:
    import: optional:file:${WH_EXTRA_CONFIG_YML_FILE:config/yml}
  data:
    mongodb:
      uri: ${WH_MONGODB_URI:mongodb://localhost/wh-db}
  rabbitmq:
    host: ${WH_AMQP_HOST}
    virtual-host: ${WH_AMQP_V_HOST}
    username: ${WH_AMQP_USERNAME}
    password: ${WH_AMQP_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${WH_IAM_ISSUER_URI}
          jwk-set-uri: ${WH_IAM_JWK_SET_URI}
          jws-algorithm: ${WH_IAM_JWS_ALG}
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  info:
    git:
      mode: full
logging:
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} - %X{dd.trace_id:-0} %X{dd.span_id:-0} - %m%n%wEx"
