spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://10.0.0.103:8000/auth/realms/webhookie
          jwk-set-uri: http://10.0.0.103:8000/auth/realms/webhookie/protocol/openid-connect/certs
          jws-algorithm: RS256
webhookie:
  security:
    audience: account
    login-url: http://localhost:8080
    groups:
      jwk-json-path: $.groups
    roles:
      jwk-json-path: $.realm_access.roles
      auto-assign-consumer: true
      role-mapping:
        USER: WH_USER
        ADMIN: WH_ADMIN
        PROVIDER: WH_PROVIDER
        CONSUMER: WH_CONSUMER