spring:
  security:
    user:
      name: wh-user
      password: password
logging:
  level:
    com.hookiesolutions.webhookie: DEBUG
webhookie:
  security:
    allowed-origins: http://localhost:4200, http://localhost:4201
