spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://webhookie.au.auth0.com/
          jwk-set-uri: https://webhookie.au.auth0.com/.well-known/jwks.json
          jws-algorithm: RS256
