spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://webhookie.au.auth0.com/
          jwk-set-uri: https://webhookie.au.auth0.com/.well-known/jwks.json
          jws-algorithm: RS256
webhookie:
  security:
    audience: KbsOSWkS6GWvmh20mg24UdnrKwgUMfvK
    login-url: http://localhost:8080
    groups:
      jwk-json-path: $['https://webhookie.com/groups']
    roles:
      jwk-json-path: $['https://webhookie.com/roles']
      auto-assign-consumer: true
      role-mapping:
        USER: WH_USER
        ADMIN: WH_ADMIN
        PROVIDER: WH_PROVIDER
        CONSUMER: WH_CONSUMER