version: '3.9'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:12.0.1
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
    - 9900:9990
    - 8000:8080
  webhookie-kc:
    image: hookiesolutions/webhookie:1.0.0
    volumes:
      - ./kc-roles.yml:/etc/webhookie/roles.yml
    environment:
      - WH_DB_USERNAME=wh-dev-user
      - WH_DB_PASSWORD=5wOA2OYzb8NWN6TJ
      - WH_DB_HOST=cluster0.dglao.mongodb.net
      - WH_DB_NAME=wh-dev-db
      - WH_AMQP_PASSWORD=CGc2Q72jafhBj3dk0uycGDxAVfe8JAPt
      - WH_AMQP_V_HOST=nbcwvmaw
      - WH_AMQP_USERNAME=nbcwvmaw
      - WH_AMQP_HOST=vulture.rmq.cloudamqp.com
      - WH_IAM_ISSUER_URI=http://10.0.0.103:8000/auth/realms/webhookie
      - WH_IAM_JWK_SET_URI=http://10.0.0.103:8000/auth/realms/webhookie/protocol/openid-connect/certs
      - WH_IAM_JWS_ALG=RS256
      - WH_SECURITY_AUD=account
      - WH_SECURITY_CLIENT_ID=webhookie-client
      - WH_SECURITY_ROLES_JSON_PATH=$$.realm_access.roles
      - WH_SECURITY_GROUPS_JSON_PATH=$$.groups
      - WH_SECURITY_EMAIL_JSON_PATH=$$.email
      - WH_SECURITY_ENTITY_JSON_PATH=$$.entity
      - WH_SECURITY_AUTO_ASSIGN_CONSUMER_ROLE=true
      - WH_SECURITY_OAUTH2_AUTHORIZATION_URI=/protocol/openid-connect/auth
      - WH_SECURITY_OAUTH2_TOKEN_URI=/protocol/openid-connect/token
      - WH_SECURITY_OAUTH2_TOKEN_NAME=access_token
      - SPRING_CONFIG_IMPORT=optional:file:/etc/webhookie/roles.yml
    ports:
      - 8082:8080
    links:
      - keycloak:keycloak
  webhookie-auth0:
    image: hookiesolutions/webhookie:1.0.0
    volumes:
      - ./auth0-roles.yml:/etc/webhookie/roles.yml
    environment:
      - WH_DB_USERNAME=wh-dev-user
      - WH_DB_PASSWORD=5wOA2OYzb8NWN6TJ
      - WH_DB_HOST=cluster0.dglao.mongodb.net
      - WH_DB_NAME=wh-dev-db
      - WH_AMQP_PASSWORD=CGc2Q72jafhBj3dk0uycGDxAVfe8JAPt
      - WH_AMQP_V_HOST=nbcwvmaw
      - WH_AMQP_USERNAME=nbcwvmaw
      - WH_AMQP_HOST=vulture.rmq.cloudamqp.com
      - WH_IAM_ISSUER_URI=https://webhookie.au.auth0.com/
      - WH_IAM_JWK_SET_URI=https://webhookie.au.auth0.com/.well-known/jwks.json
      - WH_IAM_JWS_ALG=RS256
      - WH_SECURITY_AUD=nvKDmIK9Q5Zw1UKwpON8LE3tg9vZcXb4
      - WH_SECURITY_CLIENT_ID=nvKDmIK9Q5Zw1UKwpON8LE3tg9vZcXb4
      - WH_SECURITY_ROLES_JSON_PATH=$$['https://webhookie.com/roles']
      - WH_SECURITY_GROUPS_JSON_PATH=$$['https://webhookie.com/groups']
      - WH_SECURITY_EMAIL_JSON_PATH=$$.email
      - WH_SECURITY_ENTITY_JSON_PATH=$$['https://webhookie.com/entity']
      - WH_SECURITY_AUTO_ASSIGN_CONSUMER_ROLE=true
      - WH_SECURITY_OAUTH2_AUTHORIZATION_URI=authorize
      - WH_SECURITY_OAUTH2_TOKEN_URI=oauth/token
      - WH_SECURITY_OAUTH2_TOKEN_NAME=id_token
      - SPRING_CONFIG_IMPORT=optional:file:/etc/webhookie/roles.yml
    ports:
      - 8081:8080
volumes:
  kc-roles.yml:
  auth0-roles.yml:
