version: '3.9'

volumes:
  mongodb_data:

networks:
  webhookie:

services:
  mongodb:
    image: mongo:4
    volumes:
      - 'mongodb_data:/data/db'
    container_name: webhookie-db
    ports:
      - "27017:27017"
    networks:
      webhookie:

  keycloak:
    image: quay.io/keycloak/keycloak:14.0.0
    volumes:
      - ./realm-export.json:/var/data/webhookie/realm.json
      - ./kc-add-user.json:/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json
    container_name: webhookie-keycloack
    environment:
      - KEYCLOAK_IMPORT=/var/data/webhookie/realm.json
    ports:
      - "9900:9990"
      - "8800:8080"
    networks:
      webhookie:

  webhookie:
    container_name: webhookie-server
    image: hookiesolutions/webhookie:1
    environment:
      - WH_IAM_ISSUER_URI=http://localhost:8800/auth/realms/webhookie
      - WH_IAM_JWK_SET_URI=http://keycloak:8080/auth/realms/webhookie/protocol/openid-connect/certs
      - WH_IAM_JWS_ALG=RS256
      - WH_SECURITY_AUD=webhookie_client
      - WH_SECURITY_CLIENT_ID=webhookie_client
      - WH_SECURITY_ROLES_JSON_PATH=$$.resource_access.webhookie_client.roles
      - WH_SECURITY_GROUPS_JSON_PATH=$$.groups
      - WH_SECURITY_ENTITY_JSON_PATH=$$.entity
      - WH_SECURITY_AUTO_ASSIGN_CONSUMER_ROLE=true
      - WH_SECURITY_OAUTH2_AUTHORIZATION_URI=/protocol/openid-connect/auth
      - WH_SECURITY_OAUTH2_TOKEN_URI=/protocol/openid-connect/token
      - WH_MONGODB_URI=mongodb://mongodb/webhookie-db?retryWrites=true&w=majority&maxPoolSize=200
      - WEBHOOKIE_SECURITY_ALLOWED-ORIGINS=http://localhost:4300
    ports:
      - "4300:80"
      - "8000:8080"
    networks:
      webhookie:
    depends_on:
      - mongodb
