version: '3.9'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:14.0.0
    volumes:
      - ./realm-export.json:/var/data/webhookie/realm.json
      - ./kc-add-user.json:/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json
#      - ./add-kc-user.cli:/opt/jboss/startup-scripts/add-kc-user.cli
    environment:
#      - KEYCLOAK_USER=admin
#      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/var/data/webhookie/realm.json
    ports:
    - "9900:9990"
    - "8800:8080"
  webhookie:
    image: hookiesolutions/webhookie:1.0.0
    environment:
      - WH_IAM_ISSUER_URI=http://localhost:8800/auth/realms/webhookie
      - WH_IAM_JWK_SET_URI=http://keycloak:8080/auth/realms/webhookie/protocol/openid-connect/certs
      - WH_IAM_JWS_ALG=RS256
      - WH_SECURITY_AUD=webhookie_client
      - WH_SECURITY_CLIENT_ID=webhookie_client
      - WH_SECURITY_ROLES_JSON_PATH=$$.resource_access.webhookie_client.roles
      - WH_SECURITY_GROUPS_JSON_PATH=$$.groups
      - WH_SECURITY_ENTITY_JSON_PATH=$$.entity
      - WH_SECURITY_AUTO_ASSIGN_CONSUMER_ROLE=true
      - WH_SECURITY_OAUTH2_AUTHORIZATION_URI=/protocol/openid-connect/auth
      - WH_SECURITY_OAUTH2_TOKEN_URI=/protocol/openid-connect/token
      - WH_MONGODB_URI=mongodb+srv://wh-dev-user:5wOA2OYzb8NWN6TJ@cluster0.dglao.mongodb.net/wh-dev-db?retryWrites=true&w=majority
      - WEBHOOKIE_SECURITY_ALLOWED-ORIGINS=http://localhost:4300
    ports:
      - "4300:80"
      - "8000:8080"
