POST {{host}}/company
Accept: application/json
Content-Type: application/json

{
    "name": "Hookie Solutions",
    "subscriptions": [
        {
            "name": "Order Subscription",
            "topic": "Order",
            "callbackUrl": "http://localhost:9000/wh/order",
            "httpMethod": "POST",
            "callbackSecurity": {
                "method": "HMAC",
                "secret": "SECRET-1"
            }
        },
        {
            "name": "Product Subscription",
            "topic": "Product",
            "callbackUrl": "http://localhost:9000/wh/product",
            "httpMethod": "POST",
            "callbackSecurity": {
                "method": "HMAC",
                "secret": "SECRET-2"
            }
        },
        {
            "name": "Weather Subscription",
            "topic": "Weather",
            "callbackUrl": "http://localhost:9000/wh/weather",
            "httpMethod": "POST",
            "callbackSecurity": {
                "method": "HMAC",
                "secret": "SECRET-3"
            }
        }
    ]
}

###

POST {{host}}/consumer/publish
Accept: text/plain
Content-Type: application/json
wh-topic: Foo-json
wh-trace-id: 32452345dh344553
wh-authorized-subscriber: Subscriber1
wh-authorized-subscriber: Subscriber2

{
    "name": "Me new Endpoint - 5",
    "path": "/foo-5"
}

###

POST {{host}}/consumer/publish
Accept: text/plain
Content-Type: application/xml
wh-topic: Foo-xml
wh-trace-id: 32452345dh344553
wh-authorized-subscriber: Subscriber1-xml
wh-authorized-subscriber: Subscriber2-xml

<body>
    <name>Me new Endpoint - 5</name>
    <path>/foo-5</path>
</body>

###
