POST {{host}}/consumer/publish
Accept: text/plain
Content-Type: application/json
wh-topic: Product
wh-trace-id: 32452345dh344553

< data.json

###

POST {{host}}/consumer/publish
Accept: text/plain
Content-Type: application/xml
wh-topic: Product
wh-trace-id: 32452345dh344553

< data.xml

###

POST {{host}}/consumer/publish
Accept: text/plain
Content-Type: application/json
wh-topic: Product
wh-trace-id: 32452345dh344553
wh-authorized-subscriber: 5fc8de26be1b366fc295b6c1
wh-authorized-subscriber: 5fc9b096a3b9e573df7fb15f

< data.json

###

POST {{host}}/consumer/publish
Accept: text/plain
Content-Type: application/json
wh-topic: Product
wh-trace-id: 32452345dh344553
wh-authorized-subscriber: 1
wh-authorized-subscriber: 2

< data.json

###

POST {{host}}/consumer/publish
Accept: text/plain
Content-Type: application/xml
wh-topic: Weather
wh-trace-id: 32452345dh344553
wh-authorized-subscriber: 5fc8de26be1b366fc295b6c1
wh-authorized-subscriber: 5fc9c3971995f258e6547743

< data.xml

###
