POST http://localhost:8080/applications/619eba6c18c9cf31bba331b2/callbacks
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "test 1",
  "httpMethod": "POST",
  "url": "https://subscriptionsample.webhookie.com/htest?hmac=1",
  "securityScheme": {
    "method": "HMAC",
    "details": {
      "secret": "kid",
      "keyId": "kid"
    }
  }
}

###

POST http://localhost:8080/applications/619eba6c18c9cf31bba331b2/callbacks
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "my callback1",
  "applicationId": "app",
  "httpMethod": "POST",
  "url": "http://localhost:9090",
  "securityScheme": {
    "method": "OAUTH2",
    "details": {
      "type": "CLIENT_CREDENTIALS",
      "tokenEndpoint": "https://webhookie.au.auth0.com/oauth/token",
      "clientId": "CLIENT_ID",
      "secret": "SECRET"
    }
  }
}

###

POST http://localhost:8080/applications/619eba6c18c9cf31bba331b2/callbacks
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "my callback",
  "applicationId": "app",
  "httpMethod": "POST",
  "url": "http://localhost"
}

###

GET http://localhost:8080/applications/619eba6c18c9cf31bba331b2/callbacks
Authorization: Bearer {{token}}
Accept: application/json
