POST https://webhookie.au.auth0.com/oauth/token HTTP/1.1
Accept: application/json
Authorization: Basic KbsOSWkS6GWvmh20mg24UdnrKwgUMfvK FPMZ4m4Xea6_rGjkldDje8kKchf0ZHLyKHxiAUZa2uz4zHgCcShFqQYdn0jS0sVd
cache-control: no-cache
Content-Type: application/x-www-form-urlencoded

password=weqzox-teGkec-zithu8&username=bidadh@gmail.com&grant_type=password

> response-handlers/token.js

###

POST {{host}}/oauth/token HTTP/1.1
Accept: application/json
Authorization: Basic oAuthClientAppID secret
cache-control: no-cache
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token&refresh_token={{refresh_token}}

> ../myson-auth-service/http-requests/response-handlers/token.js